### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by Lucia361** [0x410c/ClrDumper#1]
I am facing issue while compiling HookClr.
It is showing me error >>> 

cannot open file 'C:\Users\Lucy\Downloads\ClrDumper-master\ClrDumper-master\packages\minhook.1.3.3\build\native\..\..\lib\native\lib\libMinHook.lib'	HookClr	C:\Users\Lucy\Downloads\ClrDumper-master\ClrDumper-master\HookClr\LINK

Can you please upload compiled version ?

**Comment by 0x410c** [comment]
retry after restoring nuget packages, minhook is a dependency used to hook.

**Comment by 0x410c** [comment]
if you have then change the name of the lib in the folder described in error, minhook nuget package has a problem with newer vs versions

**Comment by 0x410c** [comment]
i will upload a compiled version but it will take time, 2-3 days

**Comment by 0x410c** [comment]
removed minhookl nuget package and added, compiled version.

**Comment by 0x410c** [comment]
https://github.com/0x410c/ClrDumper/releases
pre release now availabe

**Comment by Lucia361** [comment]
Thank you so much.
