### ISSUE TITLE
the clrdumper does not work

### ISSUE THREAD

**Issue by zzfeed** [0x410c/ClrDumper#2]
after run this,nothing found!!!
clrdumper F:\de4dot_All_Version\ExtremeDumper\CLRDUMP\TestInjection.exe F:\de4dot_All_Version\ExtremeDumper\CLRDUMP\HookClr.dll
Entry Point : 0x45126c
Allocated : 0x5b0000

**Comment by 0x410c** [comment]
check out the new version, now u just need 

clrdumper -nativeclr [PATH_TO_YOUR_EXE]
