### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by Phongvngg1** [0x410c/ClrDumper#3]
i used command clrdumper -nativeclr "D:\PanelT\Runtime Broker.exe" 
![image](https://user-images.githubusercontent.com/87188286/172032170-749fc4c5-4f8a-485b-ba6a-86c3d62ce3c6.png)
i checked clrdumper folder
![image](https://user-images.githubusercontent.com/87188286/172032167-585f5333-0bd2-4d95-88ff-cba5ac800b41.png)

**Comment by Phongvngg1** [comment]
.... after restart cmd, it works wtf

**Comment by 0x410c** [comment]
can u give exact steps?

**Comment by Phongvngg1** [comment]
> i think its not x64 program so it stucks

**Comment by 0x410c** [comment]
yes the build is for x86! not tested on x64
