### ISSUE TITLE
Native CLR with Anti Dump/Debug fails to dump

### ISSUE THREAD

**Issue by 0x11DFE** [0x410c/ClrDumper#4]
https://user-images.githubusercontent.com/43712252/174234914-d73f7e4e-acd6-4551-9227-b0288d559f9c.mp4

You can find the executable on [Tuts4You](https://forum.tuts4you.com/topic/43072-dumpme-debugme/). I made it a few years ago. Have fun.

**Comment by 0x410c** [comment]
I guess u detect for modification in the called function before calling it, like int3 but in my case because of the hook it detects as a debugger. I have not checked it till now, but I think it will be cool! Thanks

**Comment by 0x410c** [comment]
I was wrong lol, it detects the parent process(still not sure) , but yea adding parent spoofing for that.

**Comment by 0x410c** [comment]
i think it does not use clrcreateinstance and all to load .net assembly, right? it is not supported.

**Comment by 0x11DFE** [comment]
> i think it does not use clrcreateinstance and all to load .net assembly, right? it is not supported.

The app is fully managed, and I would have no doubt it's clr loaded.

**Comment by 0x410c** [comment]
obviously it a .net application, there is no doubt about that, but clrdumper is not a dumper like extremedumper or scylla dump, its a tool to dynamically dump .net, vbscript, jscript which are dynamically loaded for e.g. in a crypter or malware.
